name: CI Build for Windows 10+ x64
run-name: ${{ (github.event.inputs.environment) || (github.event.pull_request.title) || 'CI' }} Build for Windows 10+ x64

on: 
  workflow_dispatch: 
    inputs:
      build-type:
        description: 'Build type (Debug/Release)'
        required: false
        type: string
        default: 'Release'
      release-ver:
        description: 'Release Version (v3.0.0)'
        required: false
        type: string
        default: 'v3.0.0'
      environment:
        description: 'Environment to run in'
        type: environment
        default: CI
        required: false
  pull_request:
  workflow_call:
    inputs:
      build-type:
        description: 'Build type (Debug/Release)'
        required: false
        type: string
        default: 'Debug'
      release-ver:
        description: 'Release Version (v3.0.0)'
        required: false
        type: string      
        default: 'v3.0.0'        
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

# NOTE Secrets can NOT be accessed from PRs if they are NOT a branch on this repo!
# Please try to quit forgetting that! i know who I'm talking about, you in the mirror!

jobs:
  build_windows-2025:
    runs-on: windows-2025
    permissions: write-all
    environment: ${{ inputs.environment || 'CI' }}
   
    steps:
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v5

    - name: Setup build directory
      run: mkdir build

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.3'
        target: 'desktop'
        arch: 'win64_llvm_mingw'
        tools: 'tools_llvm_mingw1706'
        modules: 'qtmultimedia qtserialport'
        cache: true
        dir: 'D:/a/JS8Call-improved/JS8Call-improved/local/qt693'

    - name: Fetch js8lib
      run: |
        curl -L -o js8lib.zip "https://github.com/JS8Call-improved/js8lib/releases/download/lib%2F3.0/js8lib3.0_Win64.zip"

    - name: Expand js8lib archive
      run: |
        Expand-Archive js8lib.zip -DestinationPath .

    - name: Configure JS8Call
      run: |
        cd ./build
        $env:Path = "$env:GITHUB_WORKSPACE\js8lib\bin;$env:Path"
        $qt6dir = $env:Qt6_DIR
        $workspace = $env:GITHUB_WORKSPACE
        $llvm = "$env:IQTA_TOOLS\llvm-mingw1706_64\bin"
        $env:Path = "$llvm;$env:Path"
        cmake -G "Ninja Multi-Config" `
          -DCMAKE_C_COMPILER="$llvm\clang.exe" `
          -DCMAKE_CXX_COMPILER="$llvm\clang++.exe" `
          -DQt6_DIR="$qt6dir" `
          -DCMAKE_PREFIX_PATH="$workspace/js8lib;$workspace/js8lib/lib64-msvc-14.3/cmake/Boost-1.89.0" ..

    - name: Build JS8Call (CI build)
      if: ${{ !(inputs.environment) || (inputs.environment == 'CI') }}
      run: |
        cd ./build
        cmake --build . --config Debug

    - name: Build JS8Call (Release build)
      if: ${{ inputs.environment == 'Release' }}
      run: |
        cd ./build
        cmake --build . --config Release
        
    - name: Check build dir
      run: |
        cd ./build
        Get-ChildItem -Recurse
        
# Make next step for Release as well
    - name: Move exe into install directory (CI build)
      if: ${{ !(inputs.environment) || (inputs.environment == 'CI') }}
      run: |
        cp ./build/Debug/JS8Call.exe ./build/JS8Call/
        
    - name: Move libraries and License to install directory
      run: |
        cd ./build/
        cp $env:GITHUB_WORKSPACE/LICENSE JS8Call/
        cp $env:GITHUB_WORKSPACE/js8lib/dll/*.dll JS8Call/

    - name: Get secrets (CI)
      if: ${{ !(inputs.environment) || (inputs.environment == 'CI') }}
      run: |
        echo "${{ secrets.CI_CODE_SIGNING_PFX_BASE64 }}" > 'D:/a/JS8Call-improved/cert.base64'
        certutil -decode 'D:/a/JS8Call-improved/cert.base64' 'D:/a/JS8Call-improved/certificate.pfx'
      continue-on-error: true

    - name: Get secrets (Release)
      if: ${{ inputs.environment == 'Release' }}
      run: |
        echo "${{ secrets.RELEASE_CODE_SIGNING_PFX_BASE64 }}" > 'D:/a/JS8Call-improved/cert.base64'
        certutil -decode 'D:/a/JS8Call-improved/cert.base64' 'D:/a/JS8Call-improved/certificate.pfx'
      continue-on-error: false

    - name: Sign JS8Call (CI)
      if: ${{ !(inputs.environment) || (inputs.environment == 'CI') }}
      env: 
        PFX_CERTIFICATE_PASSWORD: ${{ secrets.CI_PFX_CERTIFICATE_PASSWORD }}
      run: |
        cd ./build/JS8Call/
        & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.26100.0/x64/signtool.exe' sign /fd SHA256 /v /f 'D:/a/JS8Call-improved/certificate.pfx' /p "$env:PFX_CERTIFICATE_PASSWORD" *.exe
        & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.26100.0/x64/signtool.exe' sign /fd SHA256 /v /f 'D:/a/JS8Call-improved/certificate.pfx' /p "$env:PFX_CERTIFICATE_PASSWORD" libhamlib*.dll
        & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.26100.0/x64/signtool.exe' sign /fd SHA256 /v /f 'D:/a/JS8Call-improved/certificate.pfx' /p "$env:PFX_CERTIFICATE_PASSWORD" libusb*.dll
        & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.26100.0/x64/signtool.exe' sign /fd SHA256 /v /f 'D:/a/JS8Call-improved/certificate.pfx' /p "$env:PFX_CERTIFICATE_PASSWORD" libwinpthread*.dll
        & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.26100.0/x64/signtool.exe' sign /fd SHA256 /v /f 'D:/a/JS8Call-improved/certificate.pfx' /p "$env:PFX_CERTIFICATE_PASSWORD" libfftw3*.dll
      continue-on-error: true

    - name: Sign JS8Call (Release)
      if: ${{ inputs.environment == 'Release' }}
      env: 
        PFX_CERTIFICATE_PASSWORD: ${{ secrets.RELEASE_PFX_CERTIFICATE_PASSWORD }}
      run: |
        cd ./build/JS8Call/
        & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.26100.0/x64/signtool.exe' sign /fd SHA256 /v /f 'D:/a/JS8Call-improved/certificate.pfx' /p "$env:PFX_CERTIFICATE_PASSWORD" *.exe
        & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.26100.0/x64/signtool.exe' sign /fd SHA256 /v /f 'D:/a/JS8Call-improved/certificate.pfx' /p "$env:PFX_CERTIFICATE_PASSWORD" libhamlib*.dll
        & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.26100.0/x64/signtool.exe' sign /fd SHA256 /v /f 'D:/a/JS8Call-improved/certificate.pfx' /p "$env:PFX_CERTIFICATE_PASSWORD" libusb*.dll
        & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.26100.0/x64/signtool.exe' sign /fd SHA256 /v /f 'D:/a/JS8Call-improved/certificate.pfx' /p "$env:PFX_CERTIFICATE_PASSWORD" libwinpthread*.dll
        & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.26100.0/x64/signtool.exe' sign /fd SHA256 /v /f 'D:/a/JS8Call-improved/certificate.pfx' /p "$env:PFX_CERTIFICATE_PASSWORD" libfftw3*.dll
      continue-on-error: false

    - name: Check build/JS8Call dir
      run: |
        cd ./build/JS8Call
        Get-ChildItem -Recurse
        
    - name: INNO Setup (Release build)
      if: ${{ (inputs.environment == 'Release') && (inputs.release-ver) }}
      run: |
        cd ./build/
        & 'C:/Program Files (x86)/Inno Setup 6/ISCC.exe' /F"JS8Call-installer-${{ inputs.release-ver }}" ../.github/workflows/scripts/ci-windows-installer.iss

    - name: INNO Setup (CI build)
      if: ${{ !(inputs.environment) || (inputs.environment == 'CI') }}
      run: |
        cd ./build/
        & 'C:/Program Files (x86)/Inno Setup 6/ISCC.exe' /F"JS8Call-installer-devel" ../.github/workflows/scripts/ci-windows-installer.iss

    - name: Installer signtool run (CI build)
      if: ${{ !(inputs.environment) || (inputs.environment == 'CI') }}
      env:
        PFX_CERTIFICATE_PASSWORD: ${{ secrets.CI_PFX_CERTIFICATE_PASSWORD }}
      run: |
        cd ./build/JS8Call/
        & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.26100.0/x64/signtool.exe' sign /fd SHA256 /v /f 'D:/a/JS8Call-improved/certificate.pfx' /p "$env:PFX_CERTIFICATE_PASSWORD" JS8Call-installer-*.exe
      continue-on-error: true

    - name: Installer signtool run (Release build)
      if: ${{ inputs.environment == 'Release' }}
      env:
        PFX_CERTIFICATE_PASSWORD: ${{ secrets.RELEASE_PFX_CERTIFICATE_PASSWORD }}
      run: |
        cd ./build/JS8Call/
        & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.26100.0/x64/signtool.exe' sign /fd SHA256 /v /f 'D:/a/JS8Call-improved/certificate.pfx' /p "$env:PFX_CERTIFICATE_PASSWORD" JS8Call-installer-*.exe
      continue-on-error: false
      
    - name: Attestation (Release Only)
      if: ${{ (inputs.environment == 'Release') && (inputs.release-ver) }}
      uses: actions/attest-build-provenance@v3
      with:
        subject-path: '${{ github.workspace }}/build/JS8Call/*'
        
    - name: Upload Artifact (Release build)
      if: ${{ (inputs.environment == 'Release') && (inputs.release-ver) }}
      uses: actions/upload-artifact@v6
      with:
        name: "JS8call-improved-${{ inputs.release-ver }}"
        path: |
          ./build/JS8Call/JS8Call-installer*

    - name: Upload Artifact (CI build)
      if: ${{ !(inputs.environment) || (inputs.environment == 'CI') }}
      uses: actions/upload-artifact@v6
      with:
        name: "JS8call-improved-devel"
        path: |
          ./build/JS8Call/JS8Call-installer*
#          ./build/JS8Call/
# Above to stop Chris from bitching about not understanding why this is done